/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BookingBookingIdRouteImport } from './routes/booking.$bookingId'
import { Route as BookTripIdRouteImport } from './routes/book.$tripId'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingIdRoute = BookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTripIdRoute = BookTripIdRouteImport.update({
  id: '/book/$tripId',
  path: '/book/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$tripId': typeof BookTripIdRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$tripId': typeof BookTripIdRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$tripId': typeof BookTripIdRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trips'
    | '/admin/login'
    | '/book/$tripId'
    | '/booking/$bookingId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trips'
    | '/admin/login'
    | '/book/$tripId'
    | '/booking/$bookingId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/trips'
    | '/admin/login'
    | '/book/$tripId'
    | '/booking/$bookingId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TripsRoute: typeof TripsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BookTripIdRoute: typeof BookTripIdRoute
  BookingBookingIdRoute: typeof BookingBookingIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$bookingId': {
      id: '/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof BookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$tripId': {
      id: '/book/$tripId'
      path: '/book/$tripId'
      fullPath: '/book/$tripId'
      preLoaderRoute: typeof BookTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TripsRoute: TripsRoute,
  AdminLoginRoute: AdminLoginRoute,
  BookTripIdRoute: BookTripIdRoute,
  BookingBookingIdRoute: BookingBookingIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
