/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DriverSignupRouteImport } from './routes/driver.signup'
import { Route as DriverLoginRouteImport } from './routes/driver.login'
import { Route as BookingBookingIdRouteImport } from './routes/booking.$bookingId'
import { Route as BookTripIdRouteImport } from './routes/book.$tripId'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverSignupRoute = DriverSignupRouteImport.update({
  id: '/driver/signup',
  path: '/driver/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverLoginRoute = DriverLoginRouteImport.update({
  id: '/driver/login',
  path: '/driver/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingIdRoute = BookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTripIdRoute = BookTripIdRouteImport.update({
  id: '/book/$tripId',
  path: '/book/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$tripId': typeof BookTripIdRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/signup': typeof DriverSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$tripId': typeof BookTripIdRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/signup': typeof DriverSignupRoute
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$tripId': typeof BookTripIdRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/signup': typeof DriverSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trips'
    | '/admin/login'
    | '/book/$tripId'
    | '/booking/$bookingId'
    | '/driver/login'
    | '/driver/signup'
    | '/admin/'
    | '/driver/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trips'
    | '/admin/login'
    | '/book/$tripId'
    | '/booking/$bookingId'
    | '/driver/login'
    | '/driver/signup'
    | '/admin'
    | '/driver'
  id:
    | '__root__'
    | '/'
    | '/trips'
    | '/admin/login'
    | '/book/$tripId'
    | '/booking/$bookingId'
    | '/driver/login'
    | '/driver/signup'
    | '/admin/'
    | '/driver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TripsRoute: typeof TripsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BookTripIdRoute: typeof BookTripIdRoute
  BookingBookingIdRoute: typeof BookingBookingIdRoute
  DriverLoginRoute: typeof DriverLoginRoute
  DriverSignupRoute: typeof DriverSignupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/signup': {
      id: '/driver/signup'
      path: '/driver/signup'
      fullPath: '/driver/signup'
      preLoaderRoute: typeof DriverSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/login': {
      id: '/driver/login'
      path: '/driver/login'
      fullPath: '/driver/login'
      preLoaderRoute: typeof DriverLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$bookingId': {
      id: '/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof BookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$tripId': {
      id: '/book/$tripId'
      path: '/book/$tripId'
      fullPath: '/book/$tripId'
      preLoaderRoute: typeof BookTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TripsRoute: TripsRoute,
  AdminLoginRoute: AdminLoginRoute,
  BookTripIdRoute: BookTripIdRoute,
  BookingBookingIdRoute: BookingBookingIdRoute,
  DriverLoginRoute: DriverLoginRoute,
  DriverSignupRoute: DriverSignupRoute,
  AdminIndexRoute: AdminIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
