name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run build

      - run: npx cap sync android

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - run: chmod +x android/gradlew

      - run: |
          cd android
          ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
